
package eu.mihalyi;

import javax.enterprise.event.Event;
import javax.inject.Inject;
import javax.swing.JLabel;

/**
 *
 * @author ondrej.mihalyi
 */
class MainFrame extends javax.swing.JFrame {

    @Inject Event<ChangeValueAction> changeValueAction;

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        messageOutput.setText("");
        valueDeltaMessageOutput.setText("");
    }

    public JLabel getLabel() {
        return resultOutput;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultOutput = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        valueDeltaInput = new javax.swing.JSpinner();
        deductButton = new javax.swing.JButton();
        messageOutput = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valueDeltaMessageOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultOutput.setText("0");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deductButton.setText("Deduct");
        deductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductButtonActionPerformed(evt);
            }
        });

        messageOutput.setText("MSG");

        jLabel1.setText("Result:");

        valueDeltaMessageOutput.setText("MSG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultOutput)
                        .addGap(18, 18, 18)
                        .addComponent(messageOutput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueDeltaMessageOutput)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valueDeltaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deductButton)))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultOutput)
                    .addComponent(jLabel1)
                    .addComponent(messageOutput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(valueDeltaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueDeltaMessageOutput)
                .addGap(221, 221, 221))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        changeValueAction.fire(ChangeValueAction.plus(getValueDelta()));
    }//GEN-LAST:event_addButtonActionPerformed

    private void deductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductButtonActionPerformed
        changeValueAction.fire(ChangeValueAction.minus(getValueDelta()));
    }//GEN-LAST:event_deductButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addButton;
    protected javax.swing.JButton deductButton;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel messageOutput;
    protected javax.swing.JLabel resultOutput;
    protected javax.swing.JSpinner valueDeltaInput;
    protected javax.swing.JLabel valueDeltaMessageOutput;
    // End of variables declaration//GEN-END:variables

    public int getValueDelta() {
        return ((Integer) valueDeltaInput.getValue());
    }

}
